---
sudo: required
services:
  - docker

env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage

before_install:
  - docker pull node:14

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm $NPM_TARGET

after_success:
  - set -x -v;
    set -e;
    if ["${NPM_TARGET}" = "test"]; then
      docker tag probot-hello probot-hello:$(git rev-parse HEAD)
    else
      echo "skipping dokcer tag";
    fi;
    docker images;
    set +x +v;
